### ISSUE TITLE
can't run example app

### ISSUE THREAD

**Issue by ghost** [JanezStupar/flutter_systray#1]
hello, it's a cool idea to create this plugin
but I can't run your example flutter app
I run it with this command: hover run and see in console:

`# flutter_systray_example/go/cmd
ld: warning: object file (/var/folders/hh/nnbfq8xs4nj4wqvpgxgj_zbw0000gn/T/go-link-178596472/000043.o) was built for newer macOS version (10.11) than being linked (10.10)
ld: warning: object file (/var/folders/hh/nnbfq8xs4nj4wqvpgxgj_zbw0000gn/T/go-link-178596472/000044.o) was built for newer macOS version (10.11) than being linked (10.10)
ld: warning: dylib (/Users/jwd25/Library/Caches/hover/engine/darwin/FlutterEmbedder.framework/FlutterEmbedder) was built for newer macOS version (10.11) than being linked (10.10)
hover: Successfully compiled executable binary for darwin
hover: Build finished, starting app...
hover: Running flutter_systray_example in debug mode
go-flutter: WARNING error creating the resource window: VersionUnavailable: NSGL: Failed to create OpenGL context
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(108)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(108)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/
hover: Connecting hover to 'flutter_systray_example' for hot reload
2020-10-06 11:30:32.345 flutter_systray_example[8866:99464] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1677.104/Foundation/Misc.subproj/NSUndoManager.m:363
2020-10-06 11:30:32.348 flutter_systray_example[8866:99464] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3721cb57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff700925bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff37245d08 +[NSException raise:format:arguments:] + 88
        3   Foundation                          0x00007fff39937e9d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
        4   Foundation                          0x00007fff398745ee +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 440
        5   AppKit                              0x00007fff3440165c -[NSApplication run] + 864
        6   flutter_systray_example             0x0000000004250311 nativeLoop + 81
        7   flutter_systray_example             0x000000000424ef92 _cgo_c2a8566d32ce_Cfunc_nativeLoop + 34
        8   flutter_systray_example             0x000000000406d630 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff7138233a m=3 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff7138233a
stack: frame={sp:0x70000a016548, fp:0x0} stack=[0x700009f98340,0x70000a017f40)
000070000a016448:  0000000000000080  0000000000000080 
000070000a016458:  000070000a0168a0  0000000000000000 
000070000a016468:  0000000006ab7000  000070000a0164a0 
000070000a016478:  000070000a0164b0  0000000000000080 
000070000a016488:  0000000000000000  0000000032aaaba2 
000070000a016498:  0000000000000000  0000000000000000 
000070000a0164a8:  000070000a0165e0  0000000000000000 
000070000a0164b8:  0000000032aaaba2  0000000000000000 
000070000a0164c8:  0000000000000000  0000000000000000 
000070000a0164d8:  0000000000000000  0000000000000000 
000070000a0164e8:  0000000000000000  0000000000000000 
000070000a0164f8:  0000000000000003  0000000000000000 
000070000a016508:  0000000000000000  00007fff9795de58 
000070000a016518:  00007fff9795a628  00007fff712c3065 
000070000a016528:  0000000000000000  000070000a016570 
000070000a016538:  00007fff712c58ed  0000000000000000 
000070000a016548: <00007fff7143ee60  0000000000000003 
000070000a016558:  000070000a0166f0  000070000a016590 
000070000a016568:  00007fff9795a620  000070000a0165b0 
000070000a016578:  00007fff71309808  69d5d2f83302006f 
000070000a016588:  000070000a0166b0  00007000fffff9df 
000070000a016598:  ffffffff00000008  000070000a0166b0 
000070000a0165a8:  00007fff6e56b301  000070000a0166e0 
000070000a0165b8:  00007fff6e568458  0000003000000018 
000070000a0165c8:  000070000a0166f0  000070000a016600 
000070000a0165d8:  0000000000000000  0000003000000018 
000070000a0165e8:  000070000a0166f0  000070000a016600 
000070000a0165f8:  0000000000000000  0000000000000000 
000070000a016608:  00007fff6e56b35c  00007fff3758feff 
000070000a016618:  00007fff700aa530  00007fff3758ff0a 
000070000a016628:  ffffffffffffffc9  0000000000000000 
000070000a016638:  0000000000000000  0000000000000000 
runtime: unknown pc 0x7fff7138233a
stack: frame={sp:0x70000a016548, fp:0x0} stack=[0x700009f98340,0x70000a017f40)
000070000a016448:  0000000000000080  0000000000000080 
000070000a016458:  000070000a0168a0  0000000000000000 
000070000a016468:  0000000006ab7000  000070000a0164a0 
000070000a016478:  000070000a0164b0  0000000000000080 
000070000a016488:  0000000000000000  0000000032aaaba2 
000070000a016498:  0000000000000000  0000000000000000 
000070000a0164a8:  000070000a0165e0  0000000000000000 
000070000a0164b8:  0000000032aaaba2  0000000000000000 
000070000a0164c8:  0000000000000000  0000000000000000 
000070000a0164d8:  0000000000000000  0000000000000000 
000070000a0164e8:  0000000000000000  0000000000000000 
000070000a0164f8:  0000000000000003  0000000000000000 
000070000a016508:  0000000000000000  00007fff9795de58 
000070000a016518:  00007fff9795a628  00007fff712c3065 
000070000a016528:  0000000000000000  000070000a016570 
000070000a016538:  00007fff712c58ed  0000000000000000 
000070000a016548: <00007fff7143ee60  0000000000000003 
000070000a016558:  000070000a0166f0  000070000a016590 
000070000a016568:  00007fff9795a620  000070000a0165b0 
000070000a016578:  00007fff71309808  69d5d2f83302006f 
000070000a016588:  000070000a0166b0  00007000fffff9df 
000070000a016598:  ffffffff00000008  000070000a0166b0 
000070000a0165a8:  00007fff6e56b301  000070000a0166e0 
000070000a0165b8:  00007fff6e568458  0000003000000018 
000070000a0165c8:  000070000a0166f0  000070000a016600 
000070000a0165d8:  0000000000000000  0000003000000018 
000070000a0165e8:  000070000a0166f0  000070000a016600 
000070000a0165f8:  0000000000000000  0000000000000000 
000070000a016608:  00007fff6e56b35c  00007fff3758feff 
000070000a016618:  00007fff700aa530  00007fff3758ff0a 
000070000a016628:  ffffffffffffffc9  0000000000000000 
000070000a016638:  0000000000000000  0000000000000000 

goroutine 6 [syscall]:
runtime.cgocall(0x424ef70, 0xc000046798, 0xc000026660)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000046768 sp=0xc000046730 pc=0x400863b
github.com/getlantern/systray._Cfunc_nativeLoop(0xc000000000)
        _cgo_gotypes.go:119 +0x49 fp=0xc000046798 sp=0xc000046768 pc=0x41e4fa9
github.com/getlantern/systray.nativeLoop(...)
        /Users/jwd25/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray_nonwindows.go:23
github.com/getlantern/systray.Run(0xc000026660, 0x4334a40)
        /Users/jwd25/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray.go:75 +0x3a fp=0xc0000467b8 sp=0xc000046798 pc=0x41e483a
github.com/JanezStupar/flutter_systray/go.(*FlutterSystrayPlugin).initSystrayHandler.func2(0xc000026660)
        /Users/jwd25/go/pkg/mod/github.com/!janez!stupar/flutter_systray/go@v0.1.1/plugin.go:112 +0x37 fp=0xc0000467d8 sp=0xc0000467b8 pc=0x4246637
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000467e0 sp=0xc0000467d8 pc=0x406da01
created by github.com/JanezStupar/flutter_systray/go.(*FlutterSystrayPlugin).initSystrayHandler
        /Users/jwd25/go/pkg/mod/github.com/!janez!stupar/flutter_systray/go@v0.1.1/plugin.go:111 +0x279

goroutine 1 [runnable, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEventsTimeout(0x3f9999999999999a)
        _cgo_gotypes.go:2440 +0x45
github.com/go-gl/glfw/v3.3/glfw.WaitEventsTimeout(0x3f9999999999999a)
        /Users/jwd25/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:994 +0x2d
github.com/go-flutter-desktop/go-flutter.(*Application).Run.func12(0x3f9999999999999a)
        /Users/jwd25/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/application.go:351 +0x2d
github.com/go-flutter-desktop/go-flutter.(*EventLoop).WaitForEvents(0xc00007f050, 0x4334ad8)
        /Users/jwd25/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/event-loop.go:120 +0x5ef
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc000170000, 0x0, 0x0)
        /Users/jwd25/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/application.go:350 +0x1251
github.com/go-flutter-desktop/go-flutter.Run(0xc00000e480, 0x4, 0x4, 0xc000153f68, 0x2)
        /Users/jwd25/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/application.go:26 +0x4d
main.main()
        /Users/jwd25/Documents/Work/flutter_projects/flutter_systray/example/go/cmd/main.go:24 +0x17d

goroutine 20 [chan receive]:
github.com/getlantern/systray.Register.func2(0xc0000b0060, 0xc000026660)
        /Users/jwd25/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray.go:90 +0x34
created by github.com/getlantern/systray.Register
        /Users/jwd25/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray.go:89 +0xe5

rax    0x0
rbx    0x70000a018000
rcx    0x70000a016548
rdx    0x0
rdi    0xd03
rsi    0x6
rbp    0x70000a016570
rsp    0x70000a016548
r8     0x70000a016410
r9     0x70000a0165e0
r10    0x70000a018000
r11    0x246
r12    0xd03
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7fff7138233a
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
hover: App 'flutter_systray_example' exited with error: exit status 2`

**Comment by JanezStupar** [comment]
Hey unknown user. Yes I am already aware of this issue. ATM `flutter_systray` does not work on MacOS.

The reason is that both `flutter` and  `systray` library need access to OpenGL on main thread.

I am already looking into potential solutions.

**Comment by jWinterDay** [comment]
ok, thanks. windows and linux work correct ?

**Comment by JanezStupar** [comment]
I have now managed to find an approach that allows all three desktop platforms to work correctly.

ATM it is not possible to replace systray menu in Windows (because it uses a different library) implementation. But since I don't need it ATM it will have to wait for another day.
