### ISSUE TITLE
popOver screen

### ISSUE THREAD

**Issue by khizar1556** [JanezStupar/flutter_systray#7]
Can you please tell me is it possible to make popover screen using this ?
<img width="686" alt="67123957-d7b6bb00-f1f1-11e9-8de8-b4931bf9b580" src="https://user-images.githubusercontent.com/32544554/125167671-29b82500-e1bb-11eb-9f4f-d3187d7df28c.png">

like this

**Comment by JanezStupar** [comment]
Yes that is the idea. However it is limited to text only menus.

Not even icons are supported ATM.

**Comment by khizar1556** [comment]
@JanezStupar can you please tell me i have to work in go language or dart for this? i will do this

**Comment by JanezStupar** [comment]
Both. See the example app.
